---
- name: Create RKE2 Config Directory
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Deploy RKE2 Agent Config
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: '0600'
  notify: Restart RKE2 Agent

- name: Install RKE2 Agent
  ansible.builtin.shell: curl -sfL https://get.rke2.io | sh -
  args:
    creates: /usr/local/bin/rke2
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
    INSTALL_RKE2_TYPE: "agent"
    INSTALL_RKE2_METHOD: "tar"

- name: Enable and Start RKE2 Agent
  ansible.builtin.service:
    name: rke2-agent
    state: started
    enabled: true
  ignore_errors: true

- name: Add RKE2 binaries to GLOBAL PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/rke2.sh
    content: 'export PATH=$PATH:/var/lib/rancher/rke2/bin'
    mode: '0644'
